### ISSUE TITLE
查任何货币都说查询不到

### ISSUE THREAD

**Issue by Cathgao** [SonderXiaoming/money_exchange_rate#2]
已经是最新的commit

![image](https://user-images.githubusercontent.com/21031564/222037724-867c7e09-8fbe-4e74-820a-8830995d8cd9.png)

**Comment by SonderXiaoming** [comment]
看看是不是缺xlrd的库

**Comment by Cathgao** [comment]
手动安装了xlrd之后，虽然不提示定义的问题了，但还是查不了汇率
ne能否提供完整的依赖表？
![image](https://user-images.githubusercontent.com/21031564/222996285-0a172b74-86c5-4999-abd9-a2f2e4ddf138.png)

**Comment by SonderXiaoming** [comment]
https://github.com/watermellye/money_exchange_rate
被重写了，你去那边直接git clone就行
